package handlers

import (
	"first_project/config"
	"first_project/models"
	"fmt"
	"net/http"
	"time"

	"github.com/jung-kurt/gofpdf"
)

func pdfHeader(pdf *gofpdf.Fpdf) {
	// Logo (left)
	pdf.Image("assets/logo.png", 10, 10, 20, 0, false, "", 0, "")

	// Move cursor to the right of logo
	pdf.SetXY(35, 12)

	// College Name
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "ABC College of Engineering")
	pdf.Ln(6)

	// College Info
	pdf.SetFont("Arial", "", 10)
	pdf.SetX(35)
	pdf.Cell(0, 6, "Address: Pune, Maharashtra")
	pdf.Ln(5)

	pdf.SetX(35)
	pdf.Cell(0, 6, "Phone: 9876543210 | Email: info@abccollege.edu")
	pdf.Ln(8)

	// Line separator
	pdf.Line(10, pdf.GetY(), 287, pdf.GetY())

	pdf.Ln(5)
}

func pdfFooter(pdf *gofpdf.Fpdf, username string) {
	pdf.SetY(-20)

	// Line above footer
	pdf.Line(10, pdf.GetY(), 287, pdf.GetY())

	pdf.Ln(5)

	// Footer text
	pdf.SetFont("Arial", "", 9)

	currentTime := time.Now().Format("02 Jan 2006 15:04")
	leftText := "Generated by: " + username + " | " + currentTime
	rightText := "Page " + fmt.Sprintf("%d", pdf.PageNo())

	// Left side
	pdf.CellFormat(0, 6, leftText, "", 0, "L", false, 0, "")

	// Right side
	pdf.CellFormat(0, 6, rightText, "", 0, "R", false, 0, "")
}

func DownloadStudentsPDF(w http.ResponseWriter, r *http.Request) {

	rows, err := config.DB.Query(`
SELECT id, student_name, address, state, district, taluka,
       email, mobile_number, blood_group
FROM students
	`)

	if err != nil {
		http.Error(w, "Failed to fetch students", http.StatusInternalServerError)
		return
	}
	defer rows.Close()

	var students []models.Student

	for rows.Next() {
		var s models.Student
		rows.Scan(
			&s.ID,
			&s.StudentName,
			&s.Address,
			&s.State,
			&s.District,
			&s.Taluka,
			&s.Email,
			&s.MobileNumber,
			&s.BloodGroup,
		)
		students = append(students, s)
	}

	pdf := gofpdf.New("L", "mm", "A4", "")

	pdf.SetAutoPageBreak(true, 25)

	username := "Admin"

	pdf.SetHeaderFunc(func() {
		pdfHeader(pdf)
	})

	pdf.SetFooterFunc(func() {
		pdfFooter(pdf, username)
	})

	pdf.AddPage()
	pdf.Ln(5)
	pdf.SetFont("Arial", "B", 12)
	pdf.CellFormat(0, 10, "Student List", "", 1, "C", false, 0, "")
	pdf.Ln(3)

	colWidths := []float64{
		12, // ID
		35, // Name
		55, // Address
		22, // State
		28, // District
		28, // Taluka
		55, // Email
		30, // Mobile
		15, // Blood
	}
	pdf.SetFont("Arial", "B", 10)

	headers := []string{
		"ID",
		"Name",
		"Address",
		"State",
		"District",
		"Taluka",
		"Email",
		"Mobile",
		"Blood",
	}

	for i, h := range headers {
		pdf.CellFormat(colWidths[i], 8, h, "1", 0, "C", false, 0, "")
	}
	pdf.Ln(-1)

	pdf.SetFont("Arial", "", 10)

	for _, s := range students {

		pdf.CellFormat(colWidths[0], 8, fmt.Sprintf("%d", s.ID), "1", 0, "C", false, 0, "")
		pdf.CellFormat(colWidths[1], 8, s.StudentName, "1", 0, "L", false, 0, "")
		pdf.CellFormat(colWidths[2], 8, s.Address, "1", 0, "L", false, 0, "")
		pdf.CellFormat(colWidths[3], 8, s.State, "1", 0, "L", false, 0, "")
		pdf.CellFormat(colWidths[4], 8, s.District, "1", 0, "L", false, 0, "")
		pdf.CellFormat(colWidths[5], 8, s.Taluka, "1", 0, "L", false, 0, "")
		pdf.CellFormat(colWidths[6], 8, s.Email, "1", 0, "L", false, 0, "")
		pdf.CellFormat(colWidths[7], 8, s.MobileNumber, "1", 0, "L", false, 0, "")
		pdf.CellFormat(colWidths[8], 8, s.BloodGroup, "1", 0, "C", false, 0, "")

		pdf.Ln(-1)

	}

	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", "attachment; filename=students.pdf")

	err = pdf.Output(w)
	if err != nil {
		http.Error(w, "Failed to generate PDF", http.StatusInternalServerError)
		return
	}
}
