package handlers

import (
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"time"

	"first_project/config"
	"first_project/models"

	"github.com/signintech/gopdf"
)

func resolveLogoPath() string {
	wd, _ := os.Getwd()
	candidates := []string{
		filepath.Join(wd, "assets", "logo.png"),
		filepath.Join(wd, "backend", "assets", "logo.png"),
	}

	if _, thisFile, _, ok := runtime.Caller(0); ok {
		handlersDir := filepath.Dir(thisFile)
		backendDir := filepath.Clean(filepath.Join(handlersDir, ".."))
		candidates = append(candidates, filepath.Join(backendDir, "assets", "logo.png"))
	}

	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			abs, err := filepath.Abs(p)
			if err == nil {
				return abs
			}
			return p
		}
	}
	return ""
}

/* ================= MAPS ================= */

var stateMap = map[string]string{"1": "Maharashtra", "2": "Karnataka"}
var districtMap = map[string]string{
	"1": "Pune", "2": "Nagpur", "3": "Bengaluru Urban", "4": "Mysuru",
}
var talukaMap = map[string]string{
	"1": "Haveli", "2": "Shirur", "3": "Hingna", "4": "Umred",
	"5": "Bengaluru North", "6": "Bengaluru South",
	"7": "Mysuru Taluka", "8": "Nanjangud",
}

/* ================= CONSTANTS ================= */

const (
	pageWidth  = 297.0
	pageHeight = 210.0

	topMargin    = 15.0
	bottomMargin = 20.0

	rowHeight = 8.0
	cellPad   = 2.0
)

/* ================= HEADER ================= */

func drawHeader(pdf *gopdf.GoPdf) error {
	if logo := resolveLogoPath(); logo != "" {
		if err := pdf.Image(logo, 20, 15, &gopdf.Rect{W: 24, H: 24}); err != nil {
			return err
		}
	}

	pdf.SetFont("arial-bold", "", 16)
	pdf.SetXY(0, 18)
	pdf.CellWithOption(
		&gopdf.Rect{W: pageWidth, H: 8},
		"K.K.Wagh Institute of Engineering Education And Research",
		gopdf.CellOption{Align: gopdf.Center},
	)

	pdf.SetFont("arial", "", 11)
	pdf.SetY(28)
	pdf.CellWithOption(
		&gopdf.Rect{W: pageWidth, H: 6},
		"Address: Pune, Maharashtra",
		gopdf.CellOption{Align: gopdf.Center},
	)
	pdf.SetY(34)
	pdf.CellWithOption(
		&gopdf.Rect{W: pageWidth, H: 6},
		"Phone: 9876543210 | Email: info@abccollege.edu",
		gopdf.CellOption{Align: gopdf.Center},
	)

	y := 42.0
	pdf.Line(10, y, pageWidth-10, y)
	pdf.SetY(y + 10)
	return nil
}

/* ================= FOOTER ================= */

func drawFooter(pdf *gopdf.GoPdf, page int, user string) {
	pdf.SetFont("arial", "", 9)
	pdf.SetY(pageHeight - bottomMargin)

	pdf.Line(10, pdf.GetY(), pageWidth-10, pdf.GetY())
	pdf.SetY(pdf.GetY() + 6)

	pdf.SetX(10)
	pdf.Cell(nil, fmt.Sprintf(
		"Generated by: %s | %s",
		user,
		time.Now().Format("02 Jan 2006 15:04"),
	))

	pdf.SetX(pageWidth - 30)
	pdf.Cell(nil, fmt.Sprintf("Page %d", page))
}

/* ================= TABLE HELPERS ================= */

func drawCell(
	pdf *gopdf.GoPdf,
	x, y, w float64,
	text string,
	align int,
) {
	pdf.RectFromUpperLeftWithStyle(x, y, w, rowHeight, "D")

	pdf.SetXY(x+cellPad, y+2)
	pdf.CellWithOption(
		&gopdf.Rect{W: w - 2*cellPad, H: rowHeight - 4},
		text,
		gopdf.CellOption{Align: align},
	)
}

/* ================= MAIN ================= */

func DownloadStudentsPDF(w http.ResponseWriter, r *http.Request) {

	rows, err := config.DB.Query(`
		SELECT id, student_name, address, state, district, taluka,
		       email, mobile_number, blood_group
		FROM students
	`)
	if err != nil {
		http.Error(w, "DB error", 500)
		return
	}
	defer rows.Close()

	var students []models.Student
	for rows.Next() {
		var s models.Student
		rows.Scan(
			&s.ID,
			&s.StudentName,
			&s.Address,
			&s.State,
			&s.District,
			&s.Taluka,
			&s.Email,
			&s.MobileNumber,
			&s.BloodGroup,
		)
		students = append(students, s)
	}

	pdf := &gopdf.GoPdf{}

	pdf.Start(gopdf.Config{PageSize: gopdf.Rect{W: pageWidth, H: pageHeight}, Unit: gopdf.UnitMM})
	pdf.SetMargins(0, 0, 0, 0)

	pdf.AddTTFFont("arial", "C:/Windows/Fonts/arial.ttf")
	pdf.AddTTFFont("arial-bold", "C:/Windows/Fonts/arialbd.ttf")

	page := 1
	user := "Admin"

	pdf.AddPage()
	if err := drawHeader(pdf); err != nil {
		http.Error(w, "Failed to load logo: "+err.Error(), http.StatusInternalServerError)
		return
	}

	pdf.SetFont("arial-bold", "", 12)
	pdf.CellWithOption(
		&gopdf.Rect{W: pageWidth, H: 10},
		"Student List",
		gopdf.CellOption{Align: gopdf.Center},
	)
	pdf.SetY(pdf.GetY() + 8)

	colWidths := []float64{12, 35, 55, 22, 28, 28, 55, 30, 15}
	headers := []string{"ID", "Name", "Address", "State", "District", "Taluka", "Email", "Mobile", "Blood"}

	tableWidth := 0.0
	for _, w := range colWidths {
		tableWidth += w
	}
	startX := (pageWidth - tableWidth) / 2
	y := pdf.GetY()

	// Header row
	pdf.SetFont("arial-bold", "", 10)
	x := startX
	for i, h := range headers {
		drawCell(pdf, x, y, colWidths[i], h, gopdf.Center)
		x += colWidths[i]
	}
	y += rowHeight

	// Data rows
	pdf.SetFont("arial", "", 10)
	for _, s := range students {

		if y+rowHeight > pageHeight-bottomMargin {
			drawFooter(pdf, page, user)
			page++
			pdf.AddPage()
			if err := drawHeader(pdf); err != nil {
				http.Error(w, "Failed to load logo: "+err.Error(), http.StatusInternalServerError)
				return
			}
			y = pdf.GetY()

			pdf.SetFont("arial-bold", "", 10)
			x = startX
			for i, h := range headers {
				drawCell(pdf, x, y, colWidths[i], h, gopdf.Center)
				x += colWidths[i]
			}
			y += rowHeight
			pdf.SetFont("arial", "", 10)
		}

		x = startX
		drawCell(pdf, x, y, colWidths[0], fmt.Sprintf("%d", s.ID), gopdf.Center)
		x += colWidths[0]
		drawCell(pdf, x, y, colWidths[1], s.StudentName, gopdf.Left)
		x += colWidths[1]
		drawCell(pdf, x, y, colWidths[2], s.Address, gopdf.Left)
		x += colWidths[2]
		drawCell(pdf, x, y, colWidths[3], stateMap[s.State], gopdf.Left)
		x += colWidths[3]
		drawCell(pdf, x, y, colWidths[4], districtMap[s.District], gopdf.Left)
		x += colWidths[4]
		drawCell(pdf, x, y, colWidths[5], talukaMap[s.Taluka], gopdf.Left)
		x += colWidths[5]
		drawCell(pdf, x, y, colWidths[6], s.Email, gopdf.Left)
		x += colWidths[6]
		drawCell(pdf, x, y, colWidths[7], s.MobileNumber, gopdf.Left)
		x += colWidths[7]
		drawCell(pdf, x, y, colWidths[8], s.BloodGroup, gopdf.Center)

		y += rowHeight
	}

	drawFooter(pdf, page, user)

	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", "attachment; filename=students.pdf")
	pdf.Write(w)
}
