package report

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"reporting-utility/internal/db"
	"reporting-utility/internal/repository"
	"time"

	"github.com/signintech/gopdf"
)

/* ================= MAPS ================= */
var stateMap = map[string]string{"1": "Maharashtra", "2": "Karnataka"}
var districtMap = map[string]string{
	"1": "Pune", "2": "Nagpur", "3": "Bengaluru Urban", "4": "Mysuru",
}
var talukaMap = map[string]string{
	"1": "Haveli", "2": "Shirur", "3": "Hingna", "4": "Umred",
	"5": "Bengaluru North", "6": "Bengaluru South",
	"7": "Mysuru Taluka", "8": "Nanjangud",
}

/* ================= CONSTANTS ================= */
const (
	pageWidth    = 297.0
	pageHeight   = 210.0
	topMargin    = 15.0
	bottomMargin = 20.0
	rowHeight    = 8.0
	cellPad      = 2.0
)

/* ================= HELPERS ================= */

func resolveLogoPath() string {
	cwd, _ := os.Getwd()
	p := filepath.Join(cwd, "assets", "logo.png")
	if _, err := os.Stat(p); err == nil {
		return p
	}
	return ""
}

func drawHeader(pdf *gopdf.GoPdf) {
	logo := resolveLogoPath()
	if logo != "" {
		pdf.Image(logo, 20, 15, &gopdf.Rect{W: 24, H: 24})
	}

	institution := db.AppConfig.Report.Header.Institution
	if institution == "" {
		institution = "Institution Name"
	}

	pdf.SetFont("arial-bold", "", 16)
	pdf.SetXY(0, 18)
	pdf.CellWithOption(
		&gopdf.Rect{W: pageWidth, H: 8},
		institution,
		gopdf.CellOption{Align: gopdf.Center},
	)

	pdf.SetFont("arial", "", 11)
	pdf.SetY(28)
	pdf.CellWithOption(
		&gopdf.Rect{W: pageWidth, H: 6},
		db.AppConfig.Report.Header.Address,
		gopdf.CellOption{Align: gopdf.Center},
	)
	pdf.SetY(34)
	pdf.CellWithOption(
		&gopdf.Rect{W: pageWidth, H: 6},
		db.AppConfig.Report.Header.Contact,
		gopdf.CellOption{Align: gopdf.Center},
	)

	y := 42.0
	pdf.Line(10, y, pageWidth-10, y)
	pdf.SetY(y + 10)
}

func drawFooter(pdf *gopdf.GoPdf, page int) {
	pdf.SetFont("arial", "", 9)
	pdf.SetY(pageHeight - bottomMargin)

	pdf.Line(10, pdf.GetY(), pageWidth-10, pdf.GetY())
	pdf.SetY(pdf.GetY() + 6)

	pdf.SetX(10)
	pdf.Cell(nil, fmt.Sprintf(
		"Generated by: %s | %s",
		db.AppConfig.Report.Footer.GeneratedBy,
		time.Now().Format("02 Jan 2006 15:04"),
	))

	pdf.SetX(pageWidth - 30)
	pdf.Cell(nil, fmt.Sprintf("Page %d", page))
}

// Updated drawCell to accept explicit height
func drawCell(pdf *gopdf.GoPdf, x, y, w, h float64, text string, align int) {
	pdf.RectFromUpperLeftWithStyle(x, y, w, h, "D")
	pdf.SetXY(x+cellPad, y+2)
	pdf.CellWithOption(
		&gopdf.Rect{W: w - 2*cellPad, H: h - 4},
		text,
		gopdf.CellOption{Align: align},
	)
}

/* ================= MAIN GENERATOR ================= */

func GenerateStudentPDF(students []repository.Student, w io.Writer) {
	pdf := &gopdf.GoPdf{}
	pdf.Start(gopdf.Config{PageSize: gopdf.Rect{W: pageWidth, H: pageHeight}, Unit: gopdf.UnitMM})
	pdf.SetMargins(0, 0, 0, 0)

	err := pdf.AddTTFFont("arial", "./assets/fonts/arial.ttf")
	if err != nil {
		fmt.Println("Error loading font:", err)
		return
	}
	pdf.AddTTFFont("arial-bold", "./assets/fonts/arial.ttf")

	page := 1
	pdf.AddPage()
	drawHeader(pdf)

	pdf.SetFont("arial-bold", "", 12)
	pdf.CellWithOption(
		&gopdf.Rect{W: pageWidth, H: 10},
		"Student List",
		gopdf.CellOption{Align: gopdf.Center},
	)
	pdf.SetY(pdf.GetY() + 8)

	colWidths := []float64{12, 35, 55, 22, 28, 28, 55, 30, 15}
	headers := []string{"ID", "Name", "Address", "State", "District", "Taluka", "Email", "Mobile", "Blood"}

	tableWidth := 0.0
	for _, w := range colWidths {
		tableWidth += w
	}
	startX := (pageWidth - tableWidth) / 2
	y := pdf.GetY()

	// Header
	pdf.SetFont("arial-bold", "", 10)
	x := startX
	for i, h := range headers {
		drawCell(pdf, x, y, colWidths[i], rowHeight, h, gopdf.Center)
		x += colWidths[i]
	}
	y += rowHeight

	pdf.SetFont("arial", "", 10)

	for i := 0; i < len(students); i++ {
		s := students[i]

		// --- ROWSPAN LOGIC START ---
		// 1. Check if this is the start of a group (or standard row)
		isGroupStart := (i == 0) || (students[i].Email != students[i-1].Email)
		
		span := 1
		if isGroupStart {

			for j := i + 1; j < len(students); j++ {
				if students[j].Email == students[i].Email {
					span++
				} else {
					break
				}
			}
		}

		// 2. Calculate Height Needed
		heightNeeded := rowHeight
		if isGroupStart && span > 1 {
			heightNeeded = float64(span) * rowHeight
		}

		// 3. Page Break Check
		// If the *entire* merged block doesn't fit, we force a page break.
		effectivePageHeight := pageHeight - bottomMargin
		
		if y+heightNeeded > effectivePageHeight {
			drawFooter(pdf, page)
			page++
			pdf.AddPage()
			drawHeader(pdf)
			y = pdf.GetY()

			// Re-draw Header
			pdf.SetFont("arial-bold", "", 10)
			x = startX
			for k, h := range headers {
				drawCell(pdf, x, y, colWidths[k], rowHeight, h, gopdf.Center)
				x += colWidths[k]
			}
			y += rowHeight
			pdf.SetFont("arial", "", 10)
		}
		// --- ROWSPAN LOGIC END ---

		x = startX

		// ID
		drawCell(pdf, x, y, colWidths[0], rowHeight, fmt.Sprintf("%d", s.ID), gopdf.Center)
		x += colWidths[0]

		// Name
		drawCell(pdf, x, y, colWidths[1], rowHeight, s.StudentName, gopdf.Left)
		x += colWidths[1]

		// Address
		drawCell(pdf, x, y, colWidths[2], rowHeight, s.Address, gopdf.Left)
		x += colWidths[2]

		// State
		drawCell(pdf, x, y, colWidths[3], rowHeight, stateMap[s.State], gopdf.Left)
		x += colWidths[3]

		// District
		drawCell(pdf, x, y, colWidths[4], rowHeight, districtMap[s.District], gopdf.Left)
		x += colWidths[4]

		// Taluka
		drawCell(pdf, x, y, colWidths[5], rowHeight, talukaMap[s.Taluka], gopdf.Left)
		x += colWidths[5]

		// --- EMAIL (ROWSPAN CELL) ---
		if isGroupStart {
			// Draw ONE big cell with height = span * rowHeight
			h := float64(span) * rowHeight
			drawCell(pdf, x, y, colWidths[6], h, s.Email, gopdf.Left)
		}
		// If NOT group start, we skip drawing completely (the previous big cell covers this area)
		x += colWidths[6]

		// Mobile
		drawCell(pdf, x, y, colWidths[7], rowHeight, s.MobileNumber, gopdf.Left)
		x += colWidths[7]

		// Blood Group
		drawCell(pdf, x, y, colWidths[8], rowHeight, s.BloodGroup, gopdf.Center)

		y += rowHeight
	}

	drawFooter(pdf, page)
	pdf.Write(w)
}